#───────────────────────────────────────────────────────────────────────────────
# Repository Settings
# https://github.com/repository-settings/app/blob/master/docs/plugins/repository.md
# https://docs.github.com/en/rest/repos/repos?apiVersion=2022-11-28#update-a-repository
#───────────────────────────────────────────────────────────────────────────────
repository:

  # The name of the repository
  name: .github

  #──────────────────────────────────────────────────
  # "About" section (on main page)

  # A short description of the repository
  description: >
    Contains the default community health files, GitHub templates & workflows,
    and any other files that are shared with my other repositories.

  # A URL with more information about the repository
  homepage: https://github.com/TaffarelJr

  # A comma-separated list of topics to set on the repository
  topics: github, github-config
  #──────────────────────────────────────────────────





  # # A short description of the repository that will show up on GitHub

  # # A URL with more information about the repository

  # # A comma-separated list of topics to set on the repository

  # # Either `true` to make the repository private, or `false` to make it public.
  # private: false

  # # Either `true` to enable issues for this repository, `false` to disable them.
  # has_issues: true

  # # Either `true` to enable projects for this repository, or `false` to disable them.
  # # If projects are disabled for the organization, passing `true` will cause an API error.
  # has_projects: true

  # # Either `true` to enable the wiki for this repository, `false` to disable it.
  # has_wiki: true

  # # Either `true` to enable downloads for this repository, `false` to disable them.
  # has_downloads: true

  # # Updates the default branch for this repository.
  # default_branch: master

  # # Either `true` to allow squash-merging pull requests, or `false` to prevent
  # # squash-merging.
  # allow_squash_merge: true

  # # Either `true` to allow merging pull requests with a merge commit, or `false`
  # # to prevent merging pull requests with merge commits.
  # allow_merge_commit: true

  # # Either `true` to allow rebase-merging pull requests, or `false` to prevent
  # # rebase-merging.
  # allow_rebase_merge: true

  # # Either `true` to enable automatic deletion of branches on merge, or `false` to disable
  # delete_branch_on_merge: true

  # # Either `true` to enable automated security fixes, or `false` to disable
  # # automated security fixes.
  # enable_automated_security_fixes: true

  # # Either `true` to enable vulnerability alerts, or `false` to disable
  # # vulnerability alerts.
  # enable_vulnerability_alerts: true
