name: ⏱️ Performance issue
description: Report a performance issue
title: "[PERF] "
labels: [ performance ]
assignees: [ TaffarelJr ]
body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to file a performance issue! 🤗

  - type: checkboxes
    id: new-performance
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the performance issue you encountered.
      options:
      - label: I have searched the existing issues
        required: true

  - type: textarea
    id: performance-description
    attributes:
      label: Describe the solution you'd like
      description: Please give a clear and concise description of the performance issue.
    validations:
      required: true

  - type: textarea
    id: performance-data
    attributes:
      label: Add relevant data
      description: |
        Please include any benchmarks, graphs, timings, measurements, or callstacks that are relevant.
          * If possible please include text as text rather than images (so it shows up in searches).
          * If applicable please include before and after measurements.
    validations:
      required: false

  - type: textarea
    id: additional-information
    attributes:
      label: Additional Information
      description: |
        Provide any additional information such as screenshots, context, ideas, etc.
